language: r
warnings_are_errors: true
sudo: true

cran: http://cran.rstudio.com

r_binary_packages:
 - rgdal
 - sp
 - rgeos
 - rJava
 - xlsxjars

notifications:
  email:
    on_success: change
    on_failure: change
